### ISSUE TITLE
FATAL module ads7846_device not found

### ISSUE THREAD

**Issue by ArthurJam** [notro/rpi-firmware#21]
To install my screentouch, I execute the command :
 sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update

After I config how to load the modules :
flexfb  width=320  height=480  regwidth=16 init=-1,0xb0,0x0,-1,0x11,-2,250,-1,0x3A,0x55,-1,0x36,0x28,-1,0xC2,0x44,-1,0xC5,0x00,0x00,0x0,0x0,-1,0xE0,0x0F,0x1F,0x1C,0x0C,0x0F,0x08,0x48,0x98,0x37,0x0A,0x13,0x04,0x11,0x0D,0x00,-1,0xE1,0x0F,0x32,0x2E,0x0B,0x0D,0x05,0x47,0x75,0x37,0x06,0x10,0x03,0x24,0x20,0x00,-1,0xE2,0x0F,0x32,0x2E,0x0B,0x0D,0x05,0x47,0x75,0x37,0x06,0x10,0x03,0x24,0x20,0x00,-1,0x11,-1,0X29,-3

fbtft_device debug=3 rotate=90 name=flexfb speed=16000000 gpios=reset:25,dc:24,led:22
ads7846_device gpio_pendown=17 verbose=3 x_plate_ohms=100 pressure_max=255  swap_xy=1

But after a reboot, i have a curious message : Module ads7846_device not found
By the way, the touch is not working.

Do you know why this module is not available ?

Configuration: Raspberry B+ on raspbian

**Comment by notro** [comment]
Duplicate https://github.com/notro/fbtft/issues/260
