### ISSUE TITLE
FBTFT for 3.14 Linux Kernel. 

### ISSUE THREAD

**Issue by sanjayshekar** [notro/rpi-firmware#22]
Hello All, 
         I am trying to interface PH128160T LCD TFT to Am335x processor. As this LCD comes with 8 bit 8080 interface, after some search done, I thought FBTFT will be the best suit for making this LCD up running. 
We are using TI release 3.14 linux version. I included FBTFT to 3.14 compiled and modules and installed. 
But I am not able to insmod or modprobe these modules on 3.14. Because of the compatibality issue. dmesg says : fbtft_device: no symbol version for module_layout

I would like to know if any patch avaliable for FBTFT for 3.14?? also the basic cross check question, will FBTFT support 8080, 8bit LCD TFT interface?? 

Regards,
Sanju.

**Comment by notro** [comment]
FBTFT should build with 3.14. See this for your error: http://stackoverflow.com/questions/2720177/module-layout-version-incompatibility

It does support the 8080 interface. One example is itdb24 in fbtft_device.
