### ISSUE TITLE
tm022hdh26 or ili9431 not work

### ISSUE THREAD

**Issue by Jakkawad** [notro/rpi-firmware#28]
I use Model B+ on Jessie
1. Open SPI
2. sudo nano /etc/modprobe.d/raspi-blacklist.conf -> #blacklist spi-bcm2708
3. sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update
4. /boot/config.txt ->  dtparam=spi=on 
5. sudo nano /etc/modules -> fbtft_device name=tm022hdh26 gpios=dc:24,reset:25,led:18 rotate=90
6. /usr/share/X11/xorg.conf.d/99-fbturbo.conf ->  fb1
7. /boot/cmdline.txt ->  fbcon=map:10
It not work for me ,Thank you

I'm trying 4 day

**Comment by notro** [comment]
The rpi-firmware kernel is deprecated now, the official Pi kernel has all the necessary pieces.

1. sudo rpi-update
2. /boot/config.txt -> dtparam=spi=on 
3. sudo nano /etc/modules -> fbtft_device name=tm022hdh26 gpios=dc:24,reset:25,led:18 rotate=90
4. /usr/share/X11/xorg.conf.d/99-fbturbo.conf -> fb1
5. /boot/cmdline.txt -> fbcon=map:10

Now you should have /dev/fb1
If it doesn't show up, use **dmesg** to look for errors in the kernel log.
Also try loading fbtft_device manually from the command line.

**Comment by Jakkawad** [comment]
dimes = Failed to start Load Kernel Modules.

but i'm try sudo mod probe fbtft_device name=tm022hdh26 gpios=reset:25,dc:24,led:18 rotate=90 it work but not load when start

Thank you

**Comment by notro** [comment]
If you use Raspian Jessie (the latest) it uses systemd, so try this: https://github.com/notro/fbtft/wiki#make-it-permanent-arch-linux

**Comment by Jakkawad** [comment]
thank you i will try ,and it work for 3.5 inch touch screen? i order i from eBay .

**Comment by notro** [comment]
> and it work for 3.5 inch touch screen?

I don't know

**Comment by Jakkawad** [comment]
<img width="487" alt="screen shot 2558-10-16 at 12 48 17 am" src="https://cloud.githubusercontent.com/assets/12533828/10522515/bda0142a-739f-11e5-97fd-fbbf918f2f73.png">
<img width="558" alt="screen shot 2558-10-16 at 12 48 37 am" src="https://cloud.githubusercontent.com/assets/12533828/10522516/be3d9920-739f-11e5-8244-3cc8473ac7b4.png">
<img width="558" alt="screen shot 2558-10-16 at 12 49 00 am" src="https://cloud.githubusercontent.com/assets/12533828/10522517/be3da942-739f-11e5-83b0-02aaa7892096.png">

**Comment by notro** [comment]
fbtft_device apparently is loaded before spi-bcm2835 so there's no spi bus 0.
Try adding spi-bcm2835 before fbtft_device.

**Comment by Jakkawad** [comment]
thank you,i will try now

**Comment by Jakkawad** [comment]
it work!!!  THANK YOU
