### ISSUE TITLE
Update to Raspberry Pi 3

### ISSUE THREAD

**Issue by 3lue** [notro/rpi-firmware#30]
rpi-firmware isn't compatible with Raspberry Pi 3

**Comment by DatN3xus** [comment]
Raspberry Pi doesn't start up after rpi-update

**Comment by AndrewFromMelbourne** [comment]
The firmware is this repository is very old. The Raspberry Pi Foundation kernel now contains the fbtft driver, so it is no longer necessary to download the kernel/firmware from here.

**Comment by DatN3xus** [comment]
Oh, thank you for the update sir! :)
But how do I activate it? The display doesn't run with the latest raspbian and kernel... :(

**Comment by AndrewFromMelbourne** [comment]
It depends on the display that you have attached to your Raspberry Pi. I would suggest asking for help in the Raspberry Pi forums - https://www.raspberrypi.org/forums/

**Comment by Ryanphs** [comment]
Hello All. Did any of you ever get this working? If so please let me know how, I'd be really grateful.

**Comment by AndrewFromMelbourne** [comment]
@Ryanphs. You are more likely to get the information you need on the Raspberry Pi forums. You will need to know which display you are using, as there are a number of different varieties. It will also help if you say what you would like to do with the display, as once the display is set up correctly it will be just black. You can use theses display for a variety of purposes, but setting them up to do what you want can be a little tricky.
