### ISSUE TITLE
RA8875 support?

### ISSUE THREAD

**Issue by s-t-cat** [notro/rpi-firmware#7]
Cannot find RA8875 promised device using "sudo modprobe fbtft_device name=list".
Installed 2014-06-20-wheezy-raspbian-2014-07-25-fbtft-master-firmware, then sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update. SPI device is unblacklisted.
Rasb Pi B+.

Sep 15 22:01:30 raspberrypi kernel: [   71.931771] fbtft_device:  SPI devices registered:
Sep 15 22:01:30 raspberrypi kernel: [   71.931826] fbtft_device:      spidev spi0.0 500kHz 8 bits mode=0x00
Sep 15 22:01:30 raspberrypi kernel: [   71.931842] fbtft_device:      spidev spi0.1 500kHz 8 bits mode=0x00
Sep 15 22:01:30 raspberrypi kernel: [   71.931853] fbtft_device:  'fb' Platform devices registered:
Sep 15 22:01:30 raspberrypi kernel: [   71.931873] fbtft_device:      bcm2708_fb id=-1 pdata? no
Sep 15 22:01:30 raspberrypi kernel: [   71.931915] fbtft_device:  Supported displays:
Sep 15 22:01:30 raspberrypi kernel: [   71.931925] fbtft_device:      adafruit18
Sep 15 22:01:30 raspberrypi kernel: [   71.931933] fbtft_device:      adafruit18_green
Sep 15 22:01:30 raspberrypi kernel: [   71.931941] fbtft_device:      adafruit22
Sep 15 22:01:30 raspberrypi kernel: [   71.931952] fbtft_device:      adafruit22a
Sep 15 22:01:30 raspberrypi kernel: [   71.931960] fbtft_device:      adafruit13m
Sep 15 22:01:30 raspberrypi kernel: [   71.931969] fbtft_device:      er_tftm050_2
Sep 15 22:01:30 raspberrypi kernel: [   71.931976] fbtft_device:      er_tftm070_5
Sep 15 22:01:30 raspberrypi kernel: [   71.931984] fbtft_device:      flexfb
Sep 15 22:01:30 raspberrypi kernel: [   71.931992] fbtft_device:      flexpfb
Sep 15 22:01:30 raspberrypi kernel: [   71.932000] fbtft_device:      freetronicsoled128
Sep 15 22:01:30 raspberrypi kernel: [   71.932008] fbtft_device:      hx8353d
Sep 15 22:01:30 raspberrypi kernel: [   71.932016] fbtft_device:      hy28a
Sep 15 22:01:30 raspberrypi kernel: [   71.932023] fbtft_device:      hy28b
Sep 15 22:01:30 raspberrypi kernel: [   71.932031] fbtft_device:      itdb24
Sep 15 22:01:30 raspberrypi kernel: [   71.932038] fbtft_device:      itdb28
Sep 15 22:01:30 raspberrypi kernel: [   71.932046] fbtft_device:      itdb28_spi
Sep 15 22:01:30 raspberrypi kernel: [   71.932054] fbtft_device:      mi0283qt-2
Sep 15 22:01:30 raspberrypi kernel: [   71.932062] fbtft_device:      mi0283qt-9a
Sep 15 22:01:30 raspberrypi kernel: [   71.932071] fbtft_device:      mi0283qt-v2
Sep 15 22:01:30 raspberrypi kernel: [   71.932080] fbtft_device:      nokia3310
Sep 15 22:01:30 raspberrypi kernel: [   71.932089] fbtft_device:      piscreen
Sep 15 22:01:30 raspberrypi kernel: [   71.932097] fbtft_device:      pitft
Sep 15 22:01:30 raspberrypi kernel: [   71.932105] fbtft_device:      pioled
Sep 15 22:01:30 raspberrypi kernel: [   71.932113] fbtft_device:      rpi-display
Sep 15 22:01:30 raspberrypi kernel: [   71.932120] fbtft_device:      s6d02a1
Sep 15 22:01:30 raspberrypi kernel: [   71.932129] fbtft_device:      sainsmart18
Sep 15 22:01:30 raspberrypi kernel: [   71.932137] fbtft_device:      sainsmart32
Sep 15 22:01:30 raspberrypi kernel: [   71.932146] fbtft_device:      sainsmart32_fast
Sep 15 22:01:30 raspberrypi kernel: [   71.932154] fbtft_device:      sainsmart32_latched
Sep 15 22:01:30 raspberrypi kernel: [   71.932163] fbtft_device:      sainsmart32_spi
Sep 15 22:01:30 raspberrypi kernel: [   71.932170] fbtft_device:      spidev
Sep 15 22:01:30 raspberrypi kernel: [   71.932178] fbtft_device:      ssd1331
Sep 15 22:01:30 raspberrypi kernel: [   71.932186] fbtft_device:      tinylcd35
Sep 15 22:01:30 raspberrypi kernel: [   71.932195] fbtft_device:      tm022hdh26
Sep 15 22:01:30 raspberrypi kernel: [   71.932204] fbtft_device:      upd161704
Sep 15 22:01:30 raspberrypi kernel: [   71.932212] fbtft_device:      waveshare22
Sep 15 22:01:30 raspberrypi kernel: [   71.932220] fbtft_device:

**Comment by fenderrex** [comment]
are those displays supported by the Beaglebone Black?as i have recently moved my embedded project to the bone. Iv been using the er_tftm070_5 display. Sorry i'm new to device tree stuff and was wondering where one could start as well as get documentation on the wiring...

**Comment by notro** [comment]
They should work on the BBB as well, but I haven't heard of anyone using that display though.
If you load an overlay that enables one of the SPI busses and use a gpio that is already muxed as a gpio, you should be able to use fbtft_device to load the device.

For Device Tree:
I see that er_tftm070_5 uses SPI_MODE3. Use spi-cpol; and spi-cpha; like this: https://github.com/notro/fbtft/blob/master/dts/rpi.dts#L26
Apart from that look at the er_tftm070_5 entry and the DT overlay example from the BBB page.
https://github.com/notro/fbtft/wiki/BeagleBone-Black

er_tftm070_5: https://github.com/notro/fbtft/blob/master/fbtft_device.c#L325

fbtft_device tinylcd: https://github.com/notro/fbtft/blob/master/fbtft_device.c#L906
DT overlay tinylcd: https://gist.github.com/notro/48ec4ed53df6ced661d6

**Comment by fenderrex** [comment]
Okay just sat down, thank for responding so fast. I am just flying by the seat of my britches here and I am a bit over whelmed. I have installing the fb device down just the commands listed...
But telling it to use the er_tftm070_5... 
let me say what I think I know because I don't think I understand. At https://github.com/notro/fbtft/blob/master/fbtft_device.c#L356
you setup a configuration referencing a config of the ra8875 chip here https://github.com/notro/fbtft/blob/master/fb_ra8875.c as well have the ability to change some of the GPIO?
so btft_device.c is the device tree entry point?
now that I pointed out any misunderstandings I might have had, this is where I get scared to touch my keyboard.
I don't fallow the (LCD controller device) step
So I need to build the dts file for the beagle bone black Compile and Enable? what is the lcd@0 class about. I don't get what it means by "entire file https://gist.github.com/notro/48ec4ed53df6ced661d6".
I hope I dint overwhelm you. thank you for your help so far

**Comment by fenderrex** [comment]
^^ might not have been the best place to post this now that i think about it...

**Comment by notro** [comment]
This is a good start if you don't know DT overlays on the BBB: https://learn.adafruit.com/introduction-to-the-beaglebone-black-device-tree/overview

You have two choices:
1. Setup the SPI bus using DT overlay (already provided) and use fbtft_device to load the device.
2. Use DT overlay for both SPI bus and FBTFT device (need to write one)

Here's some info about what this _device_ is: https://github.com/notro/fbtft/wiki/fbtft_device
